language: objective-c 
osx_image: xcode7.3
sudo: false
before_install:
- gem uninstall cocoapods -a
- gem install cocoapods --pre
- pod --version
- pod install --repo-update
xcode_workspace: cocoapods-bug.xcworkspace
